# Generated by Django 4.1.4 on 2026-04-09 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('disciplina', models.CharField(choices=[('História', 'História'), ('Matemática', 'Matemática'), ('Geografia', 'Geografia'), ('Português', 'Português'), ('Ciências', 'Ciências'), ('Física', 'Física'), ('Química', 'Química'), ('Biologia', 'Biologia'), ('Inglês', 'Inglês'), ('Artes', 'Artes'), ('Educação Física', 'Educação Física'), ('Filosofia', 'Filosofia'), ('Sociologia', 'Sociologia'), ('Pedagogia', 'Pedagogia'), ('Outra', 'Outra')], max_length=50)),
                ('escola', models.CharField(blank=True, max_length=150, null=True)),
                ('status_conta', models.CharField(choices=[('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Em análise', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_revisao', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('disciplina', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('modelo_ia', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('bncc', models.TextField(blank=True, null=True)),
                ('metodologia', models.CharField(blank=True, max_length=255, null=True)),
                ('duracao', models.CharField(blank=True, max_length=100, null=True)),
                ('recursos', models.TextField(blank=True, null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='producoes/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('feedback_revisao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Em revisão', max_length=50)),
                ('nota_coerencia', models.IntegerField(default=0)),
                ('nota_qualidade', models.IntegerField(default=0)),
                ('nota_metodologia', models.IntegerField(default=0)),
                ('nota_avaliacao', models.IntegerField(default=0)),
                ('nota_inclusao', models.IntegerField(default=0)),
                ('nota_inovacao', models.IntegerField(default=0)),
                ('escola', models.CharField(blank=True, max_length=149, null=True)),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
