# Generated by Django 6.0.4 on 2026-04-28 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao',
            name='data_revisao',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='feedback_revisao',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='nota_avaliacao',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='nota_coerencia',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='nota_inclusao',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='nota_inovacao',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='nota_metodologia',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='nota_qualidade',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='revisor',
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='forum_anexos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos_forum', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='kipo_playground.topico')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('feedback_revisao', models.TextField(blank=True, null=True)),
                ('nota_coerencia', models.IntegerField(default=0)),
                ('nota_qualidade', models.IntegerField(default=0)),
                ('nota_metodologia', models.IntegerField(default=0)),
                ('nota_avaliacao', models.IntegerField(default=0)),
                ('nota_inclusao', models.IntegerField(default=0)),
                ('nota_inovacao', models.IntegerField(default=0)),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='kipo_playground.producao')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('producao', 'revisor')},
            },
        ),
    ]
