# Generated by Django 6.0.4 on 2026-04-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0002_remove_producao_data_revisao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='categoria',
            field=models.CharField(choices=[('Dúvida BNCC', 'Dúvida BNCC'), ('Metodologia', 'Metodologia'), ('Uso de IA', 'Uso de IA'), ('Sugestão', 'Sugestão'), ('Geral', 'Geral')], default='Geral', max_length=50),
        ),
        migrations.AddField(
            model_name='topico',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
