# Generated by Django 6.0.4 on 2026-04-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0003_topico_categoria_topico_resolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
