# Generated by Django 6.0.4 on 2026-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0004_profile_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='prompts_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
