# Generated by Django 6.0.4 on 2026-05-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0005_producao_prompts_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='bncc_computacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
