# Generated by Django 6.0.4 on 2026-05-04 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0007_conquista_alter_comentario_autor_registroxp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='icone',
            field=models.CharField(help_text='Nome do ícone Lucide (ex: trophy, star)', max_length=50),
        ),
    ]
