# Generated by Django 4.1.4 on 2026-05-05 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0008_alter_comentario_autor_alter_conquista_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='producao_base',
            field=models.ForeignKey(blank=True, help_text='Indica se esta prática foi baseada na produção de outro professor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivacoes', to='kipo_playground.producao'),
        ),
    ]
