# Generated by Django 6.0.4 on 2026-05-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0008_alter_comentario_autor_alter_conquista_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes_derivadas', to='kipo_playground.producao'),
        ),
        migrations.AddField(
            model_name='topico',
            name='referencia_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussoes_forum', to='kipo_playground.producao'),
        ),
    ]
