# Generated by Django 6.0.4 on 2026-05-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0009_producao_producao_base'),
        ('kipo_playground', '0009_producao_referencia_topico_referencia_producao'),
    ]

    operations = [
    ]
