# Generated by Django 6.0.4 on 2026-05-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0010_merge_20260506_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='referencia_producao',
        ),
        migrations.AddField(
            model_name='producao',
            name='link_material',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Externo do Material'),
        ),
    ]
