# Generated by Django 6.0.4 on 2026-06-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0011_remove_producao_referencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Reunião', 'Reunião'), ('Treinamento', 'Treinamento'), ('Visita Escolar', 'Visita Escolar'), ('Suporte', 'Suporte'), ('Outros', 'Outros')], max_length=50)),
                ('contato', models.CharField(max_length=255)),
                ('data_evento', models.DateField()),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='diario_fotos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_evento', '-criado_em'],
            },
        ),
    ]
