# Generated by Django 6.0.4 on 2026-06-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0012_diariooperacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_revisao', models.IntegerField(default=15)),
                ('xp_aprovacao', models.IntegerField(default=50)),
                ('xp_topico', models.IntegerField(default=5)),
                ('xp_comentario', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
