# Generated by Django 6.0.4 on 2026-08-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0013_configuracaoxp_disciplina_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='producao_base',
            field=models.ForeignKey(blank=True, help_text='Indica se este tópico se baseia em alguma produção aprovada da comunidade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topicos_referencia', to='kipo_playground.producao'),
        ),
    ]
