# Generated by Django 6.0.4 on 2026-08-11 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0014_topico_producao_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diariooperacao',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_diario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diariooperacao',
            name='participantes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diariooperacao',
            name='proximos_passos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diariooperacao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Resolvido', 'Resolvido')], default='Resolvido', max_length=50),
        ),
        migrations.AddField(
            model_name='diariooperacao',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diariooperacao',
            name='contato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
