# Generated by Django 6.0.4 on 2026-08-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0017_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='exibir_autor',
            field=models.BooleanField(default=True, help_text='Se marcado, exibe o nome do autor na comunidade.'),
        ),
    ]
