# Generated by Django 4.1.4 on 2026-02-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kipo_playground", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producao",
            name="nota_avaliacao",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producao",
            name="nota_coerencia",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producao",
            name="nota_inclusao",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producao",
            name="nota_inovacao",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producao",
            name="nota_metodologia",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producao",
            name="nota_qualidade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="materiajornalistica",
            name="id",
            field=models.CharField(
                default="48998279", max_length=255, primary_key=True, serialize=False
            ),
        ),
    ]
