# Generated by Django 4.1.4 on 2026-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0004_alter_materiajornalistica_id_profile_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiajornalistica',
            name='id',
            field=models.CharField(default='91229897', max_length=255, primary_key=True, serialize=False),
        ),
    ]
