# Generated by Django 4.1.4 on 2026-01-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0004_alter_materiajornalistica_id_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='disciplina',
            field=models.CharField(choices=[('História', 'História'), ('Matemática', 'Matemática'), ('Geografia', 'Geografia'), ('Português', 'Português'), ('Ciências', 'Ciências'), ('Física', 'Física'), ('Química', 'Química'), ('Biologia', 'Biologia'), ('Inglês', 'Inglês'), ('Artes', 'Artes'), ('Educação Física', 'Educação Física'), ('Filosofia', 'Filosofia'), ('Sociologia', 'Sociologia'), ('Pedagogia', 'Pedagogia'), ('Outra', 'Outra')], default='Outra', max_length=50),
        ),
        migrations.AlterField(
            model_name='materiajornalistica',
            name='id',
            field=models.CharField(default='76284389', max_length=255, primary_key=True, serialize=False),
        ),
    ]
