# Generated by Django 4.1.4 on 2026-01-29 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kipo_playground', '0005_remove_profile_bio_profile_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiajornalistica',
            name='id',
            field=models.CharField(default='53119720', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('disciplina', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('modelo_ia', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('bncc', models.TextField(blank=True, null=True)),
                ('metodologia', models.CharField(blank=True, max_length=255, null=True)),
                ('duracao', models.CharField(blank=True, max_length=100, null=True)),
                ('recursos', models.TextField(blank=True, null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='producoes/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Em revisão', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
