# Generated by Django 4.1.4 on 2026-01-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0006_alter_materiajornalistica_id_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='feedback_revisao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiajornalistica',
            name='id',
            field=models.CharField(default='19367140', max_length=255, primary_key=True, serialize=False),
        ),
    ]
