# Generated by Django 4.1.4 on 2026-01-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kipo_playground', '0007_producao_feedback_revisao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='data_revisao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producao',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materiajornalistica',
            name='id',
            field=models.CharField(default='71636391', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disciplina',
            field=models.CharField(choices=[('História', 'História'), ('Matemática', 'Matemática'), ('Geografia', 'Geografia'), ('Português', 'Português'), ('Ciências', 'Ciências'), ('Física', 'Física'), ('Química', 'Química'), ('Biologia', 'Biologia'), ('Inglês', 'Inglês'), ('Artes', 'Artes'), ('Educação Física', 'Educação Física'), ('Filosofia', 'Filosofia'), ('Sociologia', 'Sociologia'), ('Pedagogia', 'Pedagogia'), ('Outra', 'Outra')], max_length=50),
        ),
    ]
